config/routes.rb
Rails.application.routes.draw do  
  root 'pages#home'
  resources :users
  resources :messages
  resources :friendships, except: [:show, :delete]
  delete 'friendships', to: 'friendships#destroy'

  get 'inbox', to: 'messages#inbox'

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'auth/:provider/callback' => 'sessions#callback'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, class_name: 'User'

end

app/models/message.rb
class Message < ApplicationRecord
	attr_reader :user_tokens

	belongs_to :sender, class_name: 'User'
	has_many :recipients
	has_many :users, through: :recipients

	def user_tokens=(ids)
		self.user_ids = ids
	end
end

app/models/recipient.rb
class Recipient < ApplicationRecord
	belongs_to :message
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	validates :username, presence: true, uniqueness: { case_sensitive: false},
						length: { minimum: 3, maximum: 25}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i 
	validates :email, presence: true, uniqueness: { case_sensitive: false},
						format: {with: VALID_EMAIL_REGEX}
	has_secure_password
	

	mount_uploader :avatar, AvatarUploader

	#Facbook login
	def self.from_omniauth(auth)
    # Check out the Auth Hash function at https://github.com/mkdynamic/omniauth-facebook#auth-hash
    email = auth[:info][:email] || "#{auth[:uid]}@facebook.com"
    user = where(email: email).first_or_initialize
    unless user.id?
    	user.username = auth[:info][:name]
    	user.password = SecureRandom.base64(10)
    	user.save!
    end
    user
  end


	#Message
	has_many :send_messages, class_name: "Message", foreign_key: :sender_id
	has_many :recipients, -> { where("is_read = false").order("created_at desc") }
	has_many :messages, through: :recipients

	#Friendship
	has_many :friendships
	has_many :friends, through: :friendships

	def friend?(friend)
		Friendship.where(user_id: self.id, friend_id: friend.id).any?
	end

	def add_friend(friend)
		unless self == friend || self.friend?(friend)
			transaction do 
				Friendship.create(user_id: self.id, friend_id: friend.id)
				Friendship.create(user_id: friend.id, friend_id: self.id)
			end
		end
	end

	def remove_friend(friend)
		transaction do 
			Friendship.find_by(user_id: self.id, friend_id: friend.id).destroy
			Friendship.find_by(user_id: friend.id, friend_id: self.id).destroy
		end
	end

	
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!!current_user
  end

  def require_user
  	if !logged_in?
  		flash[:error] = "You must be logged in to perform that action"
  		redirect_to root_path
  	end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	before_action :require_user
	before_action :set_friend, except: [:index]
	before_action :set_friendship, only: [:delete]

	def index
		@users = current_user.friends

	end

	def create
		if current_user.add_friend(@friend)
			flash[:success] = "Add Friend sucess"
			redirect_to users_path
		else

		end
	end

	def destroy
		if current_user.remove_friend(@friend)
			flash[:success] = "Unfriend success"
			redirect_to request.path
		else

		end
	end

	private
		def set_friend
			@friend = User.find(params[:friend_id])
		end

		def set_friendship
		end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :require_user
	before_action :set_user
	def index
		@messages = @user.send_messages.order("created_at desc")
	end

	def inbox
		@messages = @user.messages
	end

	def new
		@message = Message.new
		@users = @user.friends
	end

	def create
		@message = @user.send_messages.build(message_params)
		if @message.save
			flash[:success] = "Message Sent!"
			redirect_to messages_path
		else
			flash[:notice] = "Oops!"
			render 'new'
		end
	end

	def show
		@message = Message.find(params[:id])
		@recipient = Recipient.find_by(message: @message, user: @user)
		if @recipient.nil?
			flash[:error] = "You cannot read this message"
			redirect_to inbox_path
		else
			if @recipient.is_read
				flash[:error] = "This message have already been read!"
				redirect_to inbox_path
			else
				@recipient.update_attribute :is_read, true
				flash[:success] = "You have read this message!"
			end
		end 
	end

	private
		def message_params
			params.require(:message).permit(:body, :sender_id, user_tokens: [])
		end
		

		def set_user
			@user = User.find(current_user)
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		redirect_to inbox_path if logged_in?
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		session[:user_id] = user.id
  		flash[:success] = "You have successfully logged in"
  		redirect_to inbox_path
  	else
  		flash.now[:error] = "There was something wrong with your login information"
  		render 'new'
  	end
  end

  def destroy
  	session[:user_id] = nil
  	flash[:success] = "You have successfully logged out"
  	redirect_to root_path
  end

  def callback
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to inbox_path
    else
      flash.now[:error] = "There was something wrong with your login information"
      render 'new'
    end
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_user, only: [:index, :show]
	before_action :set_user, only: [:edit, :update, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	before_action :require_logout, only: [:new]
	
	def index
		@users = User.all
	end

	def show
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Your account have been created, please login to continute"
			redirect_to login_path
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if @user.update(user_params)
			flash[:success] = "Your account was updated successfully"
			redirect_to inbox_path
		else
			render 'edit'
		end

	end

	def destroy
		@user = User.find[params[:id]]
		@user.destroy
		flash[:destroy] = "This user have been deleted"
		redirect_to users_path
	end


	private
		def user_params
			params.require(:user).permit(:username, :email, :password, :password_confirmation, :avatar)
		end

		def set_user
			@user = User.find(params[:id])
		end

		def require_same_user
			if current_user != @user
				flash[:error] = "You can only edit your own account"
				redirect_to root_path
			end
		end

		def require_logout
			if logged_in?
				flash[:notice] = "You must logout before creating new account"
				redirect_to inbox_path
			end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def bootstrap_class_for flash_type
	  { success: 'alert-success', error: 'alert-danger', notice: 'alert-warning'}[flash_type.to_sym]
	end

	def flash_messages(opts = {})
	  flash.map do |msg_type, message|
	    content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade show") do
	      content_tag(:button, 'x'.html_safe, class: 'close', data: {dismiss: 'alert'}) + message
	    end
	  end.join.html_safe
	end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/index.html.erb
<h1>Friend list</h1>

<%= render 'users/user' %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <div class="container">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path %>"><h3 class="mb-0">MinaChat</h3></a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if logged_in? %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Messages
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="<%= inbox_path %>">Unread</a>
              <a class="dropdown-item" href="<%= messages_path %>">Have send</a>
              <a class="dropdown-item" href="<%= new_message_path %>">New messages</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Friends
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="<%= friendships_path %>">Friend list</a>
              <a class="dropdown-item" href="<%= users_path %>">Add friends</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.username.titleize %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="<%= edit_user_path(current_user) %>">Edit profile</a>
              <a class="dropdown-item" href="<%= logout_path %>" data-method="delete">Logout</a>
            </div>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MinaChat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navigation' %>
  	<div class="container main">
      <%= flash_messages %>
    	<%= yield %>
      <% if logged_in? %>
        <%= link_to new_message_path do %>
          <%= image_tag "pencil.png", class: "bottom" %>
        <% end %>
      <% end %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<div class="row">
	<div class="col-md-3">
	</div>

	<div class="col-md-6">
		<%= form_for @message do |f| %>

		<div class="form-group">
			<%= f.select :user_tokens, @users.collect {|x| [x.username, x.id]}, {}, {multiple: true} %>
		</div>
		<div class="form-group">
			<%= f.text_area :body, rows: "6", class: "form-control" %>
		</div>

		

		<div class="form-group">
			<%= f.submit "Sent", class: "btn btn-primary btn-block" %>
		</div>
		<% end %>
	</div>

</div>




<script type="text/javascript">
    $(document).ready(function() {
        $('#message_user_tokens').multiselect({
            buttonClass: 'btn btn-secondary',
            buttonWidth: '100%'
        });
    });
</script>

app/views/messages/inbox.html.erb
<h1>Unread messages</h1>

<% @messages.each do |message| %>
	<div class="box-list">
		<div class="box-avatar"><%= image_tag message.sender.avatar %></div>
		<div class="box-body">
			<h3><%= link_to "#{message.created_at}", message %></h3>
			<h5>Send by: <%= message.sender.username.titleize %></h5>
			<h5>Messages: <%= truncate(message.body, length: 50) %></h5>
		</div>
	</div>
<% end %>

app/views/messages/index.html.erb
<h1> Index </h1>

<% @messages.each do |message| %>
	<% message.recipients.each do |recipient| %>
		<div class="box-list">
			<div class="box-avatar"><%= image_tag recipient.user.avatar %></div>
			<div class="box-body">
				<% if recipient.is_read %>
					<h3>Status: Read at <%= recipient.updated_at %></h3>
				<% else %>
					<h3><font color="red">Status: Unread</font></h3>
				<% end %>
	
				<h5>Send to: <%= recipient.user.username.titleize %></h5>
				<h5>Messages: <%= truncate(message.body, length: 50) %></h5>
			</div>
		</div>
	<% end %>
<% end %>

app/views/messages/new.html.erb
<h1>New Message</h1>
<%= render 'messages/form' %>

app/views/messages/show.html.erb
<h1>Message</h1>

<div class="box-list">
	<div class="box-body" >
		<div class="box-title">
			<h3>Send by: <%= @message.sender.username %></h3>
			<p>At: <%= @message.created_at %></p>
		</div>
		<div class="box-text">
			<h5><%= @message.body %></h5>
		</div>
	</div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">	

	<div class="row">
		<div class="col-md-5 left">
			<div class="card">
				<div class="card-block">
					<%= render 'sessions/form' %>
				</div>
			</div>
		</div>

		<div class="col-md-7 right" align="center">
			<h1> Welcome to MinaChat </h1>
			<h5>Don't have any account?</h5>

			<a href="<%= signup_path %>" class="btn btn-danger btn-lg" >
			Create new account</a>
		</div>


	</div>

</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="alert alert-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "errors") %>
            prohibited this <%= obj.class.name %> from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
    <%= render 'shared/error', obj: @user %>
    <%= form_for @user, :html => {role: "form"} do |f| %>
      <div class="form-group">
      <div align="center">
        <div class="form-group">
          <%= image_tag @user.avatar %>
        </div>
        <div class="form-group">
        
          <label class="btn btn-secondary" style="width: 200px">
            Browse avatar <%= f.file_field :avatar , hidden: true %>
          </label>
        </div>
      </div>
      </div>
    
      <div class="form-group">        
        <%= f.label :username %> 
        <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
      </div>
      
      <div class="form-group">        
        <%= f.label :email %>     
        <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
      
      </div>
      
      <div class="form-group">        
        <%= f.label :password %>        
        <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
      </div>

      <div class="form-group">        
        <%= f.label :password_confirmation %>        
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password" %>
      </div>
      <div class="form-group">        
        <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary btn-block') %>
      </div>
      
    <% end %>

app/views/users/_user.html.erb
<% @users.each do |user| %>
	<div class="box-list">
		<%= image_tag user.avatar, class: "box-avatar" %>
	  <div class="box-body">
	    <h2 class="mt-0"><%= user.username.titleize %></h2>
	    <% unless user == current_user %>
		    <% unless current_user.friend?(user) %>
					<%= button_to "Add friend", friendships_path(friend_id: user.id), {class: 'btn btn-primary', remote: true} %>
				<% else %>
					<%= button_to "Unfriend", friendships_path(friend_id: user.id), method: :delete, class: 'btn btn-danger' %>
				<% end %>
			<% end %>
	  </div>
	</div>
<% end %>

app/views/users/edit.html.erb
<h1>User</h1>

<%= render 'users/form' %>

app/views/users/index.html.erb
<h1> All User </h1>
<%= render 'users/user' %>
	

app/views/users/new.html.erb
<h1 align="center">Sign up</h1>

<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<%= render 'form' %>
		<a href="/auth/facebook" title="Facebook" class="btn btn-facebook btn-block"><i class="fa fa-facebook fa-fw"></i> Connect with Facebook</a>
	</div>
</div>

app/views/users/show.html.erb
<h1>User's profile</h1>